sudo: required
language: cpp
dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq libqwt-dev fftw-dev libgsl0-dev qt5-qmake qt5-default libqt5script5

script:  
    - qmake
    - make release
