sudo: required
language: cpp
dist: trusty

before_install:
    # From: http://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci/16
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libqwt-dev fftw-dev libgsl0-dev qt55base qt55tools qt55svg qt55script

script:  
    - source /opt/qt55/bin/qt55-env.sh
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
