sudo: required
language: cpp
dist: trusty

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libqwt-dev fftw-dev libgsl0-dev qt55[QTPACKAGE]

script:  
    - source /opt/qt55/bin/qt55-env.sh
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4 release
