sudo: required
language: cpp

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq libqwt-qt5-dev fftw-dev libgsl0-dev qt5-qmake qt5-default

script:  
    - qmake
    - make release
