sudo: required
language: cpp
dist: trusty

before_install:
    - sudo sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
    - sudo apt-get -qq update
    - sudo apt-get install -qq libqwt-dev fftw-dev libgsl0-dev qt5-qmake qt5-default qtscript5-dev

script:  
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4 release
