language: cpp
branches:
  except:
    - "/^appveyor.*$/"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      #     - os: osx
      #       osx_image: xcode9.2
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
      sudo apt-get update -qq
      sudo apt-get install -qq libgsl0-dev qt510base qt510tools qt510svg
    else
      brew update --quiet
      brew install qt gsl
      export PATH="/usr/local/opt/qt/bin:$PATH"      
    fi
install:
  - source $TRAVIS_BUILD_DIR/contrib/travis-install.sh
script:
  - source $TRAVIS_BUILD_DIR/contrib/travis-build.sh
after_success:
  - cd source
  - find ../../example -name "example-*" -exec ./strata -b {} \;
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Z2q1ECai8J5HcnofI8v/BkI0BVPrMzibyXw9gM6+xa2kUG14yTQCnO845HN+PkSbTcMbmmILxrssytlLoibQDFad6pbJKGRKxOrI9TSqnfl79ZzX/Q9Nbq3yvpksG4lWF2XHJvN74N+yVxkw2JsFdu8ikJEv0qR242uWY5/GodNMl/w0ck+aOwtGWNmyKA86opkg9p4kA3ZxzhzGyc9jKNdob/z/gG0SHKMp4j58xxRSC1ZohI8CssVOVZpyduGJuCLxHekd/0T1VXQGGhIWKnM72GYz1BjCus47I4S2Ss4xUWL2tDHdK2lfbZLeybeVFM8cQX17gmRZeyCikl8d0BlROGGu6Hb5TbLyok4j0QC1HRq9JVNHgv+OzahqLdoKYWeCcHewOZyQQ/0RErrQzDUw9SIbdf6RMC+9WXx7eVgv8PPsqNNgkRkQIldcbN6uB2wU58x1vx3VaU22eXolDNjKbhrYGi1k8CDjnFNg8P7G4B1jOWAFUMfs3CYfj9Hmf7UUA0HJV2KyVtsNilRV10Qz8DGmIc/umXITQS3UB0klEzfzS16QWRRMKXmTCD0JLpRukkXjcKpBxgIj6JcRxGzDlMd3qYFyM2VTXfWMS4UK5eEr+x2j8Z660ErSycNUIW3TblABhbOoFHsyjbvEVojhSGExzD6l1rSspvmL60A=
  file: $APPIMAGE
  on:
    os: linux
    repo: arkottke/strata
    tags: true
  script: source $TRAVIS_BUILD_DIR/contrib/travis-deploy.sh
