sudo: required
language: cpp
dist: trusty

before_install:
    # From: http://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci/16
    - sudo add-apt-repository --yes ppa:beineri/opt-qt561-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libgsl0-dev qt56base qt56tools qt56svg qt56script
    - source /opt/qt55/bin/qt56-env.sh
    - svn checkout svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
    - cd qwt
    - qmake
    - make -j 2
    - sudo make install
    - cd ..

before_script:  
    - qmake -set INCLUDEPATH ..
    - make -j 2 release

script:
    - ./source/strata -b ../example/*.strata
    - ./source/strata -b ../example/*.json
