sudo: required
language: cpp
dist: trusty

before_install:
    # https://launchpad.net/~beineri/+archive/ubuntu/opt-qt561
    - sudo add-apt-repository --yes ppa:beineri/opt-qt561-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libgsl0-dev qt56base qt56tools qt56svg qt56script
    - source /opt/qt56/bin/qt56-env.sh
    - cd $TRAVIS_BUILD_DIR/..
    - svn checkout svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
    - cd qwt
    - qmake
    - make -j2
    - QWT_VERSION=`sed -rn 's/^#define QWT_VERSION_STR.*"([0-9]+.[0-9]+.[0-9]+)"/\1/p' src/qwt_global.h`
    - QWT_PATH=/usr/local/qwt-$QWT_VERSION-svn
    - sudo make install

script:
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - source /opt/qt56/bin/qt56-env.sh
    # Add paths for libraries
    - export LIBS="-L$QWT_PATH/lib"
    - export INCLUDEPATH="$QWT_PATH/include"
    - qmake ..
    - make -j2
    - ./release/strata -b ../example/*.strata
    - ./release/strata -b ../example/*.json
    - cd ..
