# version format
version: '{build}'

platform: x64
environment:
  fast_finish: true
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

configuration: Release
    
# Configure git linebreaks
init:
  - git config --global core.autocrlf input
  
# Install dependencies
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - pacman --noconfirm -S pacman-mirrors
  - pacman -Syu --noconfirm
  # Need to re-run Syu after update
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm mingw-w64-%ARCH%-qwt-qt5 mingw-w64-%ARCH%-gsl mingw-w64-%ARCH%-qt5

build_script:
  - C:\msys64\usr\bin\sh --login /c/projects/strata/scripts/build_msys.sh

artifacts:
    - path: Strata-mingw64-*.exe
      name: Strata Installer (64-bit)

    - path: Strata-mingw64-*.7z
      name: Strata Archive (64-bit)

    - path: Strata-mingw32-*.exe
      name: Strata Installer (32-bit)

    - path: Strata-mingw32-*.7z
      name: Strata Archive (32-bit)
