# version format
version: '{build}'

environment:
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

configuration: Release
    
# Configure git linebreaks
init:
    - git config --global core.autocrlf input
    
platform:
  - x64
  
# Install dependencies
install:
  - msys64\msys2_shell.bat
  - pacman -Sy --noconfirm pacman-mirrors
  - update-core
  - pacman -Su --noconfirm
  - pacman -S --noconfirm mingw-w64-$ARCH-qwt-qt5 mingw-w64-$ARCH-gsl mingw-w64-$ARCH-qt5


