# version format
version: '{build}'

platform: x64
environment:
  fast_finish: true
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

configuration: Release
    
# Configure git linebreaks
init:
  - git config --global core.autocrlf input
  
# Install dependencies
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - pacman --noconfirm -S pacman-mirrors
  - pacman -Syu --noconfirm
  # Need to re-run Syu after update
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm mingw-w64-%ARCH%-qwt-qt5 mingw-w64-%ARCH%-gsl mingw-w64-%ARCH%-qt5

build_script:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) 
  - C:\msys64\usr\bin\sh --login /c/projects/strata/msys_build.sh
