# version format
version: '{build}'

environment:
  fast_finish: true
  matrix:
  - ARCH: "i686"
    PATH: C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%
    MKSPEC: C:\msys64\mingw32\share\qt5\mkspecs\win32-g++
  - ARCH: "x86_64"
    PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    MKSPEC: C:\msys64\mingw32\share\qt5\mkspecs\win32-g++

configuration: Release
    
# Configure git linebreaks
init:
  - git config --global core.autocrlf input
  

# Install dependencies
install:
  - pacman --noconfirm -S pacman-mirrors
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm mingw-w64-%ARCH%-qwt-qt5 mingw-w64-%ARCH%-gsl mingw-w64-%ARCH%-qt5

build_script:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - mkdir build
  - pushd build
  - qmake ..
  - make -j2 release
  - popd
